### ISSUE TITLE
А как?

### ISSUE THREAD

**Issue by IvanGrigorik** [amateomi/BSUIR-labs#1]
Совершенно непонятно, как пользователь будет дальше решать сам. Я бы описал это ещё одним ### предложением.
https://github.com/amateomi/BSUIR-labs/blob/e401f122db78ed382cb05b66951949eea2f9da5f/TRiTPO/requirements.md?plain=1#L68

**Comment by amateomi** [comment]
Спасибо за замечание, обязательно приму к сведению

**Comment by amateomi** [comment]
Игрок будет это решать во время поиска соперника, обратитесь к mockup поиска рейтингового матча
