### ISSUE TITLE
Проверка движка?

### ISSUE THREAD

**Issue by IvanGrigorik** [amateomi/BSUIR-labs#2]
https://github.com/amateomi/BSUIR-labs/blob/cfc76c169610bd4edc6bdd23f486df335eba5d47/TRiTPO/requirements.md?plain=1#L147
Если я напишу свой движок, то, в теории, я смогу играть в свои шахматы? Или всё же нужна проверка как минимум работоспособности движка?

**Comment by amateomi** [comment]
Если ваш движок следует протоколу UCI, то вы сможете его использовать с этим приложением. Проверка на корректность игрового движка осуществляется системой автоматически.
